### ISSUE TITLE
Your ko-fi link is broken (on your website as well)

### ISSUE THREAD

**Issue by wilhelmy** [konradybcio/konradybcio#1]
Hi Konrad,

I read about your attempt to get Linux ported and running on the ipad mini 2 and I gotta say good job, I'd like to try it one day since the device is out of support and I didn't really like iOS to begin with (not the OS itself, but the way Apple keeps the thumb on everything and acts like the king of the device you bought with your own money).

By the looks of it, Linux boots but are there graphics drivers?

Just wanted to let you know that your ko-fi link is broken.

Best regards,
Moritz

**Comment by konradybcio** [comment]
> By the looks of it, Linux boots but are there graphics drivers?

The current iteration relies on the dumb framebuffer set up by iBoot.

> Just wanted to let you know that your ko-fi link is broken.

I know, I closed it. Thanks for letting me know, though.

**Comment by wilhelmy** [comment]
JFTR (and maybe you're already aware of it), it seems mesa has an open merge request for a driver for some PowerVR GPUs since 2022. I'm not sure how similar it is architecturally to the one in the A7 devices, but seems to be for some Series 6 devices so it does look like it could be relevant: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15243

Thanks again for the porting effort.
